// Type definitions (inline to avoid module issues in browser context)
interface StatusUpdate {
  step: string;
  message: string;
  success?: boolean;
  progress?: number;
}

interface DatabaseConfig {
  host: string;
  user: string;
  password: string;
  port: number;
}

// Theme Management (initialize before DOM)
function initTheme(): void {
  const savedTheme = localStorage.getItem('theme') || 'dark';
  console.log('[THEME] Initializing theme:', savedTheme);
  document.documentElement.setAttribute('data-theme', savedTheme);
}

// Initialize theme immediately
console.log('[APP] Application starting...');
initTheme();

// DOM elements (will be initialized in DOMContentLoaded)
let form: HTMLFormElement;
let projectNameInput: HTMLInputElement;
let databaseNameInput: HTMLInputElement;
let destinationPathInput: HTMLInputElement;
let generateBtn: HTMLButtonElement;
let cancelBtn: HTMLButtonElement;
let browseBtn: HTMLButtonElement;
let fullPathSpan: HTMLSpanElement;
let statusSection: HTMLDivElement;
let statusMessage: HTMLDivElement;
let dbStatusText: HTMLSpanElement;
let dbIndicator: HTMLSpanElement;
let testDbBtn: HTMLButtonElement;

// Database config inputs
let dbHost: HTMLInputElement;
let dbPort: HTMLInputElement;
let dbUser: HTMLInputElement;
let dbPassword: HTMLInputElement;
let saveDbConfigBtn: HTMLButtonElement;
let dbConfigToggle: HTMLElement;
let dbConfigSection: HTMLDivElement;

// Progress elements
let progressFill: HTMLDivElement;
let progressText: HTMLSpanElement;

// Error display elements
let projectNameError: HTMLElement;
let databaseNameError: HTMLElement;

// Theme and plugin inputs
let enableThemesCheckbox: HTMLInputElement;
let themesPathInput: HTMLInputElement;
let browseThemesBtn: HTMLButtonElement;
let enablePluginsCheckbox: HTMLInputElement;
let pluginsPathInput: HTMLInputElement;
let browsePluginsBtn: HTMLButtonElement;

// VHost section elements
let vhostSection: HTMLDivElement;
let vhostConfig: HTMLPreElement;
let hostsConfig: HTMLPreElement;
let copyVhostBtn: HTMLButtonElement;
let copyHostsBtn: HTMLButtonElement;
let vhostFilename: HTMLSpanElement;
let siteLink: HTMLAnchorElement;

// Delete project elements
let deleteProjectPath: HTMLInputElement;
let browseDeleteBtn: HTMLButtonElement;
let projectInfoSection: HTMLDivElement;
let deleteProjectName: HTMLSpanElement;
let deleteDbName: HTMLSpanElement;
let deleteDbUser: HTMLSpanElement;
let deleteDbHost: HTMLSpanElement;
let deleteDbCheckbox: HTMLInputElement;
let confirmDeleteCheckbox: HTMLInputElement;
let deleteProjectBtn: HTMLButtonElement;
let deleteStatusMessage: HTMLDivElement;

// Config page elements
let configDbHost: HTMLInputElement;
let configDbPort: HTMLInputElement;
let configDbUser: HTMLInputElement;
let configDbPassword: HTMLInputElement;
let testDbConfigBtn: HTMLButtonElement;
let saveDbConfigBtnPage: HTMLButtonElement;
let configDbStatus: HTMLDivElement;
let configDbIndicator: HTMLSpanElement;
let configDbStatusText: HTMLSpanElement;

// Navigation elements
let navLinks: NodeListOf<HTMLButtonElement>;
let pages: NodeListOf<HTMLDivElement>;

// Titlebar controls
let themeToggle: HTMLButtonElement;
let minimizeBtn: HTMLButtonElement;
let maximizeBtn: HTMLButtonElement;
let closeBtn: HTMLButtonElement;

// Status items
let statusCopy: HTMLDivElement;
let statusConfig: HTMLDivElement;
let statusDatabase: HTMLDivElement;
let statusThemes: HTMLDivElement;
let statusPlugins: HTMLDivElement;
let statusPermissions: HTMLDivElement;
let statusRollback: HTMLDivElement;

// Generation header elements
let generationHeader: HTMLDivElement;

// State
let isGenerating = false;
let lastAutoGeneratedDbName = '';
let currentProjectInfo: { path: string; name: string; isValid: boolean; wpConfig?: { dbName: string; dbUser: string; dbPassword: string; dbHost: string; dbPrefix?: string } } | null = null;

function toggleTheme(): void {
  const currentTheme = document.documentElement.getAttribute('data-theme');
  const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
  console.log('[THEME] Switching theme from', currentTheme, 'to', newTheme);
  document.documentElement.setAttribute('data-theme', newTheme);
  localStorage.setItem('theme', newTheme);
  console.log('[THEME] Theme changed successfully to:', newTheme);
}

// Update full path preview
function updateFullPath(): void {
  const projectName = projectNameInput.value || '<nom-projet>';
  const destination = destinationPathInput.value || '<destination>';
  const fullPath = `${destination}/${projectName}`;
  fullPathSpan.textContent = fullPath;
}

// Update database name based on project name
function updateDatabaseName(): void {
  const projectName = projectNameInput.value.trim();

  // Only auto-fill if database name is empty or was auto-generated
  const currentDbName = databaseNameInput.value.trim();
  const shouldAutoFill = !currentDbName || currentDbName === lastAutoGeneratedDbName;

  if (projectName && shouldAutoFill) {
    // Replace hyphens with underscores and keep only alphanumeric + underscores
    const sanitizedName = projectName.replace(/-/g, '_').replace(/[^a-zA-Z0-9_]/g, '');
    databaseNameInput.value = sanitizedName;
    lastAutoGeneratedDbName = sanitizedName;
  }
}

// Validate project name
function validateProjectName(): boolean {
  const value = projectNameInput.value.trim();
  const pattern = /^[a-zA-Z][a-zA-Z0-9_-]{0,63}$/;

  if (!value) {
    showFieldError(projectNameError, 'Le nom du projet est requis');
    return false;
  }

  if (!pattern.test(value)) {
    showFieldError(projectNameError, 'Doit commencer par une lettre (max 64 caractères)');
    return false;
  }

  hideFieldError(projectNameError);
  return true;
}

// Validate database name
function validateDatabaseName(): boolean {
  const value = databaseNameInput.value.trim();
  const pattern = /^[a-zA-Z_][a-zA-Z0-9_]{0,63}$/;

  if (!value) {
    showFieldError(databaseNameError, 'Le nom de la base de données est requis');
    return false;
  }

  if (!pattern.test(value)) {
    showFieldError(databaseNameError, 'Doit commencer par une lettre ou underscore (max 64 caractères)');
    return false;
  }

  const reserved = ['mysql', 'information_schema', 'performance_schema', 'sys'];
  if (reserved.includes(value.toLowerCase())) {
    showFieldError(databaseNameError, 'Ce nom est réservé par MySQL');
    return false;
  }

  hideFieldError(databaseNameError);
  return true;
}

function showFieldError(element: HTMLElement, message: string): void {
  element.textContent = message;
  element.classList.remove('hidden');
}

function hideFieldError(element: HTMLElement): void {
  element.classList.add('hidden');
}

// Update progress bar
function updateProgress(percent: number): void {
  progressFill.style.width = `${percent}%`;
  progressText.textContent = `${percent}%`;
}

// Update status item
function updateStatusItem(step: string, message: string, success?: boolean): void {
  console.log('[STATUS] Updating status item:', { step, message, success });
  let statusItem: HTMLDivElement | null = null;

  switch (step) {
    case 'copy':
      statusItem = statusCopy;
      break;
    case 'config':
      statusItem = statusConfig;
      break;
    case 'database':
      statusItem = statusDatabase;
      break;
    case 'themes':
      statusItem = statusThemes;
      break;
    case 'plugins':
      statusItem = statusPlugins;
      break;
    case 'permissions':
      statusItem = statusPermissions;
      break;
    case 'rollback':
      statusItem = statusRollback;
      statusItem.classList.remove('hidden');
      break;
    default:
      console.warn('[STATUS] Unknown step:', step);
      return;
  }

  if (!statusItem) {
    console.error('[STATUS] Status item not found for step:', step);
    return;
  }

  const iconElement = statusItem.querySelector('.status-icon') as HTMLSpanElement;
  if (!iconElement) {
    console.error('[STATUS] Icon element not found');
    return;
  }

  if (success === undefined) {
    // In progress
    statusItem.classList.remove('pending', 'success', 'error');
    statusItem.classList.add('in-progress');
    iconElement.textContent = '◐';
  } else if (success) {
    // Success
    statusItem.classList.remove('pending', 'in-progress', 'error');
    statusItem.classList.add('success');
    iconElement.textContent = '●';
  } else {
    // Error
    statusItem.classList.remove('pending', 'in-progress', 'success');
    statusItem.classList.add('error');
    iconElement.textContent = '✕';
  }
}

// Show message
function showMessage(text: string, type: 'info' | 'error' | 'success' = 'info'): void {
  console.log('[MESSAGE]', type.toUpperCase() + ':', text);
  statusMessage.textContent = text;
  statusMessage.className = 'status-message';
  statusMessage.classList.remove('hidden');
  if (type === 'error') {
    statusMessage.classList.add('error');
  } else if (type === 'success') {
    statusMessage.classList.add('success');
  }
}

// Update generation header state (for success/error)
function updateGenerationHeaderState(state: 'generating' | 'success' | 'error', title: string): void {
  const headerH2 = generationHeader.querySelector('h2');
  if (!headerH2) return;

  if (state === 'success') {
    headerH2.innerHTML = `
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="color: var(--status-success)">
        <path d="M22 11.08V12a10 10 0 11-5.93-9.14"/>
        <polyline points="22 4 12 14.01 9 11.01"/>
      </svg>
      ${title}
    `;
    headerH2.style.color = 'var(--status-success)';
    cancelBtn.classList.add('hidden');
  } else if (state === 'error') {
    headerH2.innerHTML = `
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="color: var(--status-error)">
        <circle cx="12" cy="12" r="10"/>
        <line x1="15" y1="9" x2="9" y2="15"/>
        <line x1="9" y1="9" x2="15" y2="15"/>
      </svg>
      ${title}
    `;
    headerH2.style.color = 'var(--status-error)';
    cancelBtn.classList.add('hidden');
  } else {
    headerH2.innerHTML = `
      <svg class="spinning-icon" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M21 12a9 9 0 11-6.219-8.56"/>
      </svg>
      ${title}
    `;
    headerH2.style.color = 'var(--accent-primary)';
    cancelBtn.classList.remove('hidden');
  }
}

// Reset status
function resetStatus(): void {
  console.log('[STATUS] Resetting all status items');
  [statusCopy, statusConfig, statusDatabase, statusThemes, statusPlugins, statusPermissions, statusRollback].forEach(item => {
    if (item) {
      item.classList.remove('in-progress', 'success', 'error');
      item.classList.add('pending');
      const iconElement = item.querySelector('.status-icon') as HTMLSpanElement;
      if (iconElement) {
        iconElement.textContent = '○';
      }
    }
  });

  // Hide optional status items
  statusThemes.classList.add('hidden');
  statusPlugins.classList.add('hidden');
  statusRollback.classList.add('hidden');

  // Reset progress
  updateProgress(0);

  statusMessage.textContent = '';
  statusMessage.className = 'status-message hidden';
}

// Enable/disable form
function setFormEnabled(enabled: boolean): void {
  console.log('[FORM] Setting form enabled:', enabled);
  isGenerating = !enabled;

  // Add/remove generating class to gray out the form
  form.classList.toggle('generating', !enabled);

  generateBtn.disabled = !enabled;
  projectNameInput.disabled = !enabled;
  databaseNameInput.disabled = !enabled;
  destinationPathInput.disabled = !enabled;
  browseBtn.disabled = !enabled;

  // Show/hide status section (with cancel button inside)
  statusSection.classList.toggle('hidden', enabled);
}

// Get current database config from form
function getDbConfigFromForm(): DatabaseConfig {
  return {
    host: dbHost.value || 'localhost',
    port: parseInt(dbPort.value, 10) || 3306,
    user: dbUser.value || 'root',
    password: dbPassword.value || ''
  };
}

// Load database config from backend
async function loadDbConfig(): Promise<void> {
  try {
    const config = await window.electronAPI.getDbConfig();
    dbHost.value = config.host;
    dbPort.value = String(config.port);
    dbUser.value = config.user;
    dbPassword.value = config.password;
    console.log('[DB] Configuration chargée');
  } catch (error) {
    console.error('[DB] Erreur lors du chargement de la config:', error);
  }
}

// Save database config
async function saveDbConfig(): Promise<void> {
  const config = getDbConfigFromForm();

  try {
    saveDbConfigBtn.disabled = true;
    saveDbConfigBtn.textContent = 'Sauvegarde...';

    const result = await window.electronAPI.updateDbConfig(config);

    if (result.success) {
      saveDbConfigBtn.textContent = 'Sauvegardé ✓';
      setTimeout(() => {
        saveDbConfigBtn.textContent = 'Sauvegarder la configuration';
        saveDbConfigBtn.disabled = false;
      }, 2000);
    } else {
      showMessage(result.message || 'Erreur lors de la sauvegarde', 'error');
      saveDbConfigBtn.textContent = 'Sauvegarder la configuration';
      saveDbConfigBtn.disabled = false;
    }
  } catch (error) {
    console.error('[DB] Erreur lors de la sauvegarde:', error);
    saveDbConfigBtn.textContent = 'Sauvegarder la configuration';
    saveDbConfigBtn.disabled = false;
  }
}

// Toggle collapsible section
function toggleDbConfigSection(): void {
  const isHidden = dbConfigSection.classList.contains('hidden');
  dbConfigSection.classList.toggle('hidden');

  const toggleIcon = dbConfigToggle.querySelector('.toggle-icon');
  if (toggleIcon) {
    toggleIcon.textContent = isHidden ? '▼' : '▶';
  }
}

// Initial DB connection test and theme init
window.addEventListener('DOMContentLoaded', async () => {
  console.log('[DOM] DOMContentLoaded event fired');

  // Initialize all DOM elements
  console.log('[DOM] Initializing DOM elements...');
  form = document.getElementById('generateForm') as HTMLFormElement;
  projectNameInput = document.getElementById('projectName') as HTMLInputElement;
  databaseNameInput = document.getElementById('databaseName') as HTMLInputElement;
  destinationPathInput = document.getElementById('destinationPath') as HTMLInputElement;
  generateBtn = document.getElementById('generateBtn') as HTMLButtonElement;
  cancelBtn = document.getElementById('cancelBtn') as HTMLButtonElement;
  browseBtn = document.getElementById('browseBtn') as HTMLButtonElement;
  fullPathSpan = document.getElementById('fullPath') as HTMLSpanElement;
  statusSection = document.getElementById('statusSection') as HTMLDivElement;
  statusMessage = document.getElementById('statusMessage') as HTMLDivElement;
  dbStatusText = document.getElementById('dbStatusText') as HTMLSpanElement;
  dbIndicator = document.getElementById('dbIndicator') as HTMLSpanElement;
  testDbBtn = document.getElementById('testDbBtn') as HTMLButtonElement;

  // Database config elements
  dbHost = document.getElementById('dbHost') as HTMLInputElement;
  dbPort = document.getElementById('dbPort') as HTMLInputElement;
  dbUser = document.getElementById('dbUser') as HTMLInputElement;
  dbPassword = document.getElementById('dbPassword') as HTMLInputElement;
  saveDbConfigBtn = document.getElementById('saveDbConfigBtn') as HTMLButtonElement;
  dbConfigToggle = document.getElementById('dbConfigToggle') as HTMLElement;
  dbConfigSection = document.getElementById('dbConfigSection') as HTMLDivElement;

  // Progress elements
  progressFill = document.getElementById('progressFill') as HTMLDivElement;
  progressText = document.getElementById('progressText') as HTMLSpanElement;

  // Error elements
  projectNameError = document.getElementById('projectNameError') as HTMLElement;
  databaseNameError = document.getElementById('databaseNameError') as HTMLElement;

  // Titlebar controls
  themeToggle = document.getElementById('themeToggle') as HTMLButtonElement;
  minimizeBtn = document.getElementById('minimizeBtn') as HTMLButtonElement;
  maximizeBtn = document.getElementById('maximizeBtn') as HTMLButtonElement;
  closeBtn = document.getElementById('closeBtn') as HTMLButtonElement;

  // Status items
  statusCopy = document.getElementById('status-copy') as HTMLDivElement;
  statusConfig = document.getElementById('status-config') as HTMLDivElement;
  statusDatabase = document.getElementById('status-database') as HTMLDivElement;
  statusThemes = document.getElementById('status-themes') as HTMLDivElement;
  statusPlugins = document.getElementById('status-plugins') as HTMLDivElement;
  statusPermissions = document.getElementById('status-permissions') as HTMLDivElement;
  statusRollback = document.getElementById('status-rollback') as HTMLDivElement;
  generationHeader = document.querySelector('.generation-header') as HTMLDivElement;

  // Theme and plugin inputs
  enableThemesCheckbox = document.getElementById('enableThemes') as HTMLInputElement;
  themesPathInput = document.getElementById('themesPath') as HTMLInputElement;
  browseThemesBtn = document.getElementById('browseThemesBtn') as HTMLButtonElement;
  enablePluginsCheckbox = document.getElementById('enablePlugins') as HTMLInputElement;
  pluginsPathInput = document.getElementById('pluginsPath') as HTMLInputElement;
  browsePluginsBtn = document.getElementById('browsePluginsBtn') as HTMLButtonElement;

  // VHost elements
  vhostSection = document.getElementById('vhostSection') as HTMLDivElement;
  vhostConfig = document.getElementById('vhostConfig') as HTMLPreElement;
  hostsConfig = document.getElementById('hostsConfig') as HTMLPreElement;
  copyVhostBtn = document.getElementById('copyVhostBtn') as HTMLButtonElement;
  copyHostsBtn = document.getElementById('copyHostsBtn') as HTMLButtonElement;
  vhostFilename = document.getElementById('vhostFilename') as HTMLSpanElement;
  siteLink = document.getElementById('siteLink') as HTMLAnchorElement;

  // Delete project elements
  deleteProjectPath = document.getElementById('deleteProjectPath') as HTMLInputElement;
  browseDeleteBtn = document.getElementById('browseDeleteBtn') as HTMLButtonElement;
  projectInfoSection = document.getElementById('projectInfoSection') as HTMLDivElement;
  deleteProjectName = document.getElementById('deleteProjectName') as HTMLSpanElement;
  deleteDbName = document.getElementById('deleteDbName') as HTMLSpanElement;
  deleteDbUser = document.getElementById('deleteDbUser') as HTMLSpanElement;
  deleteDbHost = document.getElementById('deleteDbHost') as HTMLSpanElement;
  deleteDbCheckbox = document.getElementById('deleteDbCheckbox') as HTMLInputElement;
  confirmDeleteCheckbox = document.getElementById('confirmDeleteCheckbox') as HTMLInputElement;
  deleteProjectBtn = document.getElementById('deleteProjectBtn') as HTMLButtonElement;
  deleteStatusMessage = document.getElementById('deleteStatusMessage') as HTMLDivElement;

  // Config page elements
  configDbHost = document.getElementById('configDbHost') as HTMLInputElement;
  configDbPort = document.getElementById('configDbPort') as HTMLInputElement;
  configDbUser = document.getElementById('configDbUser') as HTMLInputElement;
  configDbPassword = document.getElementById('configDbPassword') as HTMLInputElement;
  testDbConfigBtn = document.getElementById('testDbConfigBtn') as HTMLButtonElement;
  saveDbConfigBtnPage = document.getElementById('saveDbConfigBtnPage') as HTMLButtonElement;
  configDbStatus = document.getElementById('configDbStatus') as HTMLDivElement;
  configDbIndicator = document.getElementById('configDbIndicator') as HTMLSpanElement;
  configDbStatusText = document.getElementById('configDbStatusText') as HTMLSpanElement;

  // Navigation elements
  navLinks = document.querySelectorAll('.nav-link') as NodeListOf<HTMLButtonElement>;
  pages = document.querySelectorAll('.page') as NodeListOf<HTMLDivElement>;

  console.log('[DOM] All DOM elements initialized');

  // Setup event listeners
  console.log('[EVENTS] Setting up event listeners...');
  setupEventListeners();
  console.log('[EVENTS] Event listeners setup complete');

  // Load database configuration
  await loadDbConfig();

  // Auto-test DB connection on load
  console.log('[DB] Scheduling automatic DB connection test in 500ms');
  setTimeout(() => {
    console.log('[DB] Triggering automatic DB connection test');
    testDbBtn.click();
  }, 500);
});

function setupEventListeners(): void {
  // Navigation
  navLinks.forEach(link => {
    link.addEventListener('click', () => {
      const pageName = link.dataset.page;
      if (pageName) {
        navigateToPage(pageName);
      }
    });
  });

  // Theme toggle
  themeToggle.addEventListener('click', (e) => {
    e.preventDefault();
    toggleTheme();
  });

  // Window controls
  minimizeBtn.addEventListener('click', () => {
    window.electronAPI.minimizeWindow();
  });

  maximizeBtn.addEventListener('click', () => {
    window.electronAPI.maximizeWindow();
  });

  closeBtn.addEventListener('click', () => {
    window.electronAPI.closeWindow();
  });

  // Database config toggle
  dbConfigToggle.addEventListener('click', toggleDbConfigSection);

  // Save database config
  saveDbConfigBtn.addEventListener('click', saveDbConfig);

  // Form validation on input
  projectNameInput.addEventListener('input', () => {
    updateFullPath();
    updateDatabaseName();
    validateProjectName();
  });

  projectNameInput.addEventListener('blur', validateProjectName);
  databaseNameInput.addEventListener('blur', validateDatabaseName);

  destinationPathInput.addEventListener('input', updateFullPath);

  browseBtn.addEventListener('click', async () => {
    const path = await window.electronAPI.selectDirectory();
    if (path) {
      destinationPathInput.value = path;
      updateFullPath();
    }
  });

  // Cancel button
  cancelBtn.addEventListener('click', async () => {
    console.log('[CANCEL] Cancel button clicked');
    cancelBtn.disabled = true;
    cancelBtn.textContent = 'Annulation...';

    try {
      await window.electronAPI.cancelOperation();
      showMessage('Opération annulée', 'info');
    } catch (error) {
      console.error('[CANCEL] Error:', error);
    }

    cancelBtn.disabled = false;
    cancelBtn.textContent = 'Annuler';
  });

  // Theme checkbox toggle
  enableThemesCheckbox.addEventListener('change', () => {
    const enabled = enableThemesCheckbox.checked;
    themesPathInput.disabled = !enabled;
    browseThemesBtn.disabled = !enabled;
    if (enabled) {
      statusThemes.classList.remove('hidden');
    }
  });

  // Plugin checkbox toggle
  enablePluginsCheckbox.addEventListener('change', () => {
    const enabled = enablePluginsCheckbox.checked;
    pluginsPathInput.disabled = !enabled;
    browsePluginsBtn.disabled = !enabled;
    if (enabled) {
      statusPlugins.classList.remove('hidden');
    }
  });

  // Browse themes directory
  browseThemesBtn.addEventListener('click', async () => {
    const path = await window.electronAPI.selectDirectory();
    if (path) {
      themesPathInput.value = path;
    }
  });

  // Browse plugins directory
  browsePluginsBtn.addEventListener('click', async () => {
    const path = await window.electronAPI.selectDirectory();
    if (path) {
      pluginsPathInput.value = path;
    }
  });

  // Test DB connection
  testDbBtn.addEventListener('click', async () => {
    testDbBtn.disabled = true;
    dbStatusText.textContent = 'Test en cours...';
    dbIndicator.className = 'status-indicator unknown';

    try {
      const config = getDbConfigFromForm();
      const result = await window.electronAPI.testDbConnection(config);

      if (result.success) {
        dbStatusText.textContent = 'MySQL connecté';
        dbIndicator.className = 'status-indicator connected';
      } else {
        dbStatusText.textContent = `Erreur: ${result.message}`;
        dbIndicator.className = 'status-indicator disconnected';
      }
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Erreur inconnue';
      dbStatusText.textContent = `Erreur: ${errorMessage}`;
      dbIndicator.className = 'status-indicator disconnected';
    } finally {
      testDbBtn.disabled = false;
    }
  });

  // Form submission
  form.addEventListener('submit', async (e: Event) => {
    e.preventDefault();
    console.log('[FORM] Form submitted');

    // Validate fields
    const isProjectValid = validateProjectName();
    const isDbValid = validateDatabaseName();

    if (!isProjectValid || !isDbValid) {
      showMessage('Veuillez corriger les erreurs dans le formulaire', 'error');
      return;
    }

    const projectName = projectNameInput.value.trim();
    const databaseName = databaseNameInput.value.trim();
    const destinationPath = destinationPathInput.value.trim();
    const themesPath = enableThemesCheckbox.checked ? themesPathInput.value.trim() : undefined;
    const pluginsPath = enablePluginsCheckbox.checked ? pluginsPathInput.value.trim() : undefined;
    const dbConfig = getDbConfigFromForm();

    if (!projectName || !databaseName || !destinationPath) {
      showMessage('Veuillez remplir tous les champs obligatoires', 'error');
      return;
    }

    // Check if project already exists
    try {
      const existsResult = await window.electronAPI.checkProjectExists(projectName, destinationPath);
      if (existsResult.exists) {
        showMessage(`Le projet "${projectName}" existe déjà dans ce répertoire`, 'error');
        return;
      }
    } catch (error) {
      console.error('[FORM] Error checking project existence:', error);
    }

    console.log('[FORM] Starting generation...');
    resetStatus();
    statusSection.classList.remove('hidden');
    vhostSection.classList.add('hidden');

    // Show theme/plugin status items if enabled
    if (enableThemesCheckbox.checked) {
      statusThemes.classList.remove('hidden');
    }
    if (enablePluginsCheckbox.checked) {
      statusPlugins.classList.remove('hidden');
    }

    setFormEnabled(false);

    try {
      const result = await window.electronAPI.generateWordPress({
        projectName,
        databaseName,
        destinationPath,
        themesPath,
        pluginsPath,
        dbConfig
      });

      if (result.success) {
        showMessage(result.message || 'Projet généré avec succès', 'success');
        updateProgress(100);

        // Update generation header to show success
        updateGenerationHeaderState('success', 'Génération terminée !');

        // Display VHost and Hosts configurations
        if (result.vhostConfig && result.hostsEntry && result.serverName) {
          vhostSection.classList.remove('hidden');
          vhostConfig.textContent = result.vhostConfig;
          hostsConfig.textContent = result.hostsEntry;
          vhostFilename.textContent = `${projectName}.conf`;
          siteLink.href = `http://${result.serverName}`;
          siteLink.textContent = result.serverName;
        }

        // Re-enable form but keep status visible
        form.classList.remove('generating');
        generateBtn.disabled = false;
        projectNameInput.disabled = false;
        databaseNameInput.disabled = false;
        destinationPathInput.disabled = false;
        browseBtn.disabled = false;
        isGenerating = false;
      } else {
        showMessage(result.message || 'Erreur lors de la génération', 'error');
        updateGenerationHeaderState('error', 'Erreur lors de la génération');
        setFormEnabled(true);
      }
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Erreur inconnue';
      showMessage(`Erreur inattendue: ${errorMessage}`, 'error');
      updateGenerationHeaderState('error', 'Erreur inattendue');
      setFormEnabled(true);
    }
  });

  // Copy buttons for VHost configurations
  copyVhostBtn.addEventListener('click', async () => {
    try {
      await navigator.clipboard.writeText(vhostConfig.textContent || '');
      copyVhostBtn.textContent = 'Copié ✓';
      copyVhostBtn.classList.add('copied');

      setTimeout(() => {
        copyVhostBtn.textContent = 'Copier';
        copyVhostBtn.classList.remove('copied');
      }, 2000);
    } catch (error) {
      showMessage('Erreur lors de la copie', 'error');
    }
  });

  copyHostsBtn.addEventListener('click', async () => {
    try {
      await navigator.clipboard.writeText(hostsConfig.textContent || '');
      copyHostsBtn.textContent = 'Copié ✓';
      copyHostsBtn.classList.add('copied');

      setTimeout(() => {
        copyHostsBtn.textContent = 'Copier';
        copyHostsBtn.classList.remove('copied');
      }, 2000);
    } catch (error) {
      showMessage('Erreur lors de la copie', 'error');
    }
  });

  // Listen for status updates
  window.electronAPI.onStatusUpdate((data: StatusUpdate) => {
    console.log('[IPC] Received status update:', data);
    const { step, message, success } = data;
    updateStatusItem(step, message, success);
    if (step !== 'error') {
      showMessage(message, success ? 'info' : 'info');
    }
  });

  // Listen for progress updates
  window.electronAPI.onProgressUpdate((progress: number) => {
    console.log('[IPC] Received progress update:', progress);
    updateProgress(progress);
  });

  // Browse for project to delete
  browseDeleteBtn.addEventListener('click', async () => {
    const path = await window.electronAPI.selectDirectory();
    if (path) {
      deleteProjectPath.value = path;
      await loadProjectInfo(path);
    }
  });

  // Confirm delete checkbox
  confirmDeleteCheckbox.addEventListener('change', () => {
    deleteProjectBtn.disabled = !confirmDeleteCheckbox.checked;
  });

  // Config page: Test DB connection
  testDbConfigBtn.addEventListener('click', async () => {
    testDbConfigBtn.disabled = true;
    showConfigDbStatus('Test en cours...', 'unknown');

    try {
      const config = getConfigPageDbConfig();
      const result = await window.electronAPI.testDbConnection(config);

      if (result.success) {
        showConfigDbStatus('Connexion réussie', 'connected');
      } else {
        showConfigDbStatus(`Erreur: ${result.message}`, 'disconnected');
      }
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Erreur inconnue';
      showConfigDbStatus(`Erreur: ${errorMessage}`, 'disconnected');
    } finally {
      testDbConfigBtn.disabled = false;
    }
  });

  // Config page: Save DB config
  saveDbConfigBtnPage.addEventListener('click', saveConfigPageDbConfig);

  // Delete project button
  deleteProjectBtn.addEventListener('click', handleDeleteProject);
}

// Navigation function
function navigateToPage(pageName: string): void {
  console.log('[NAV] Navigating to page:', pageName);

  // Update nav links
  navLinks.forEach(link => {
    if (link.dataset.page === pageName) {
      link.classList.add('active');
    } else {
      link.classList.remove('active');
    }
  });

  // Update pages
  pages.forEach(page => {
    if (page.id === `page-${pageName}`) {
      page.classList.add('active');
    } else {
      page.classList.remove('active');
    }
  });

  // Load config page data when navigating to it
  if (pageName === 'config') {
    loadConfigPageData();
  }
}

// Load config page data from backend
async function loadConfigPageData(): Promise<void> {
  try {
    const config = await window.electronAPI.getDbConfig();
    configDbHost.value = config.host;
    configDbPort.value = String(config.port);
    configDbUser.value = config.user;
    configDbPassword.value = config.password;
    console.log('[CONFIG] Configuration loaded to config page');
  } catch (error) {
    console.error('[CONFIG] Error loading config:', error);
  }
}

// Get DB config from config page
function getConfigPageDbConfig(): DatabaseConfig {
  return {
    host: configDbHost.value || 'localhost',
    port: parseInt(configDbPort.value, 10) || 3306,
    user: configDbUser.value || 'root',
    password: configDbPassword.value || ''
  };
}

// Show config DB status
function showConfigDbStatus(message: string, status: 'connected' | 'disconnected' | 'unknown'): void {
  configDbStatus.classList.remove('hidden');
  configDbStatusText.textContent = message;
  configDbIndicator.className = 'status-indicator ' + status;
}

// Save config from config page
async function saveConfigPageDbConfig(): Promise<void> {
  const config = getConfigPageDbConfig();

  try {
    saveDbConfigBtnPage.disabled = true;
    saveDbConfigBtnPage.innerHTML = `
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M19 21H5a2 2 0 01-2-2V5a2 2 0 012-2h11l5 5v11a2 2 0 01-2 2z"/>
        <polyline points="17 21 17 13 7 13 7 21"/>
        <polyline points="7 3 7 8 15 8"/>
      </svg>
      Sauvegarde...
    `;

    const result = await window.electronAPI.updateDbConfig(config);

    if (result.success) {
      // Update the generate page DB config too
      dbHost.value = config.host;
      dbPort.value = String(config.port);
      dbUser.value = config.user;
      dbPassword.value = config.password;

      saveDbConfigBtnPage.innerHTML = `
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M22 11.08V12a10 10 0 11-5.93-9.14"/>
          <polyline points="22 4 12 14.01 9 11.01"/>
        </svg>
        Sauvegardé
      `;
      showConfigDbStatus('Configuration sauvegardée', 'connected');

      setTimeout(() => {
        saveDbConfigBtnPage.innerHTML = `
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M19 21H5a2 2 0 01-2-2V5a2 2 0 012-2h11l5 5v11a2 2 0 01-2 2z"/>
            <polyline points="17 21 17 13 7 13 7 21"/>
            <polyline points="7 3 7 8 15 8"/>
          </svg>
          Sauvegarder
        `;
        saveDbConfigBtnPage.disabled = false;
      }, 2000);
    } else {
      showConfigDbStatus(result.message || 'Erreur lors de la sauvegarde', 'disconnected');
      saveDbConfigBtnPage.innerHTML = `
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M19 21H5a2 2 0 01-2-2V5a2 2 0 012-2h11l5 5v11a2 2 0 01-2 2z"/>
          <polyline points="17 21 17 13 7 13 7 21"/>
          <polyline points="7 3 7 8 15 8"/>
        </svg>
        Sauvegarder
      `;
      saveDbConfigBtnPage.disabled = false;
    }
  } catch (error) {
    console.error('[CONFIG] Error saving config:', error);
    showConfigDbStatus('Erreur lors de la sauvegarde', 'disconnected');
    saveDbConfigBtnPage.innerHTML = `
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M19 21H5a2 2 0 01-2-2V5a2 2 0 012-2h11l5 5v11a2 2 0 01-2 2z"/>
        <polyline points="17 21 17 13 7 13 7 21"/>
        <polyline points="7 3 7 8 15 8"/>
      </svg>
      Sauvegarder
    `;
    saveDbConfigBtnPage.disabled = false;
  }
}

// Load project info for deletion
async function loadProjectInfo(projectPath: string): Promise<void> {
  console.log('[DELETE] Loading project info:', projectPath);
  showDeleteStatus('Chargement des informations du projet...', 'info');

  try {
    const info = await window.electronAPI.getProjectInfo(projectPath);
    console.log('[DELETE] Project info:', info);

    currentProjectInfo = info;

    if (info.isValid && info.wpConfig) {
      // Display project info
      deleteProjectName.textContent = info.name;
      deleteDbName.textContent = info.wpConfig.dbName;
      deleteDbUser.textContent = info.wpConfig.dbUser;
      deleteDbHost.textContent = info.wpConfig.dbHost;

      // Show project info section
      projectInfoSection.classList.remove('hidden');

      // Reset checkboxes
      deleteDbCheckbox.checked = true;
      confirmDeleteCheckbox.checked = false;
      deleteProjectBtn.disabled = true;

      showDeleteStatus('Projet WordPress valide trouvé', 'success');
    } else {
      // Hide project info section
      projectInfoSection.classList.add('hidden');
      currentProjectInfo = null;
      showDeleteStatus('Ce dossier ne semble pas être un projet WordPress valide (wp-config.php non trouvé)', 'error');
    }
  } catch (error) {
    console.error('[DELETE] Error loading project info:', error);
    projectInfoSection.classList.add('hidden');
    currentProjectInfo = null;
    showDeleteStatus('Erreur lors du chargement des informations du projet', 'error');
  }
}

// Handle project deletion
async function handleDeleteProject(): Promise<void> {
  if (!currentProjectInfo || !currentProjectInfo.isValid) {
    showDeleteStatus('Aucun projet valide sélectionné', 'error');
    return;
  }

  if (!confirmDeleteCheckbox.checked) {
    showDeleteStatus('Veuillez confirmer la suppression', 'error');
    return;
  }

  const deleteDb = deleteDbCheckbox.checked;
  const projectPath = currentProjectInfo.path;

  console.log('[DELETE] Starting project deletion:', { projectPath, deleteDb });

  // Disable buttons during deletion
  deleteProjectBtn.disabled = true;
  deleteProjectBtn.textContent = 'Suppression en cours...';
  browseDeleteBtn.disabled = true;

  showDeleteStatus('Suppression en cours...', 'info');

  try {
    const result = await window.electronAPI.deleteProject(projectPath, deleteDb);
    console.log('[DELETE] Delete result:', result);

    if (result.success) {
      let message = 'Projet supprimé avec succès';
      if (result.dbDeleted) {
        message += ' (base de données supprimée)';
      }
      showDeleteStatus(message, 'success');

      // Reset form
      deleteProjectPath.value = '';
      projectInfoSection.classList.add('hidden');
      confirmDeleteCheckbox.checked = false;
      currentProjectInfo = null;
    } else {
      showDeleteStatus(result.message || 'Erreur lors de la suppression', 'error');
    }
  } catch (error) {
    console.error('[DELETE] Error during deletion:', error);
    const errorMessage = error instanceof Error ? error.message : 'Erreur inconnue';
    showDeleteStatus(`Erreur: ${errorMessage}`, 'error');
  } finally {
    deleteProjectBtn.disabled = false;
    deleteProjectBtn.textContent = 'Supprimer le projet';
    browseDeleteBtn.disabled = false;
  }
}

// Show delete status message
function showDeleteStatus(message: string, type: 'info' | 'success' | 'error'): void {
  deleteStatusMessage.textContent = message;
  deleteStatusMessage.className = 'status-message';
  deleteStatusMessage.classList.remove('hidden');

  if (type === 'error') {
    deleteStatusMessage.classList.add('error');
  } else if (type === 'success') {
    deleteStatusMessage.classList.add('success');
  }
}
